[package]
name = "mancala-rust"
version = "0.1.0"
authors = ["Daiju Nakayama <42.daiju@gmail.com>"]
edition = "2018"

[dependencies]
rand = "*"
rand_pcg = "*"
fnv = "*"
lazy_static = "*"
ndarray = { version = "*", features = ["serde-1"] }

rust-nn = {version = "*", path = "../../rust/rust-nn" }
